### PR TITLE
Updating for ST3, latest fish builtins, indentation rules

### PR DESCRIPTION
**Pull request by Phidica**
I'm a brand new fish user, but I think I'll be using it for a while so I'm motivated to update this package

The sublime-syntax files are a lot easier to read and modify, but only compatible with ST3. I note that this package is considered ST2-compatible, so for any changes I made to the sublime-syntax I did similar in the tmLanguage. I don't know if that's going to be viable in the long term though

I've added new fish builtin commands that weren't in the syntax list before, and removed ones that don't seem to be supported any more (as of fish 2.3.1)

I've tested the indentation rules over the course of writing my config.fish file, and they seem to work pretty well. indentNextLinePattern may not be doing anything though

I forgot to branch this first, I'll try and do so in future

### CODE REVIEW

**Comment by Phidica** [comment]
It occurs to me that I did not update `fish.json-tmLanguage`. I didn't really understand what it was for, and still don't tbh. I'm guessing the deadlinked "AAAPackageDev" in the readme takes in this file and compiles it to the tmLanguage file used by ST2

I can update this file to incorporate the changes if you like

**Comment by Phidica** [comment]
Just commenting to be clear I've made all the changes I wished to and this pull is ready to go if you want it

**Comment by nhooyr** [comment]
Since the author of this plugin is now inactive, we could fork?

**Comment by Phidica** [comment]
As you may have noticed, I did fork the repo some time ago and I've put quite a lot of work into arbitrary syntax highlighting on a separate branch. It basically redoes...everything this repo had, besides the snippets. It's close enough to complete that I stopped working on it very often, but I could pick it back up if others were interested

I was initially invested in getting my changes merged to this repo because it's the one listed on the Package Control website. But it does seem to be completely inactive now

**Comment by nhooyr** [comment]
I'm definitely interested :)

You could just submit a new package to Package Control, see https://packagecontrol.io/docs/submitting_a_package

**Comment by Phidica** [comment]
Huh, that is easier than I imagined it would be

I had always figured that if I gave up on having my changes merged to this repo, I would turn my fork into a standalone repo. I will look into doing this now. Thank you for providing the impetus to do so

**Pull request closed without merging**
